var arrLang = {
    'en': {
        'all_beverages': 'All Beverages',
        'soft_drinks': 'Soft Drinks',
        'alcoholic_drinks': 'Alcoholic Drinks',
        'history_stats': 'History/Stats',
        'welcome': 'Welcome',
        'balance': 'Balance:',
        'admin_view': 'Admin view',
        'log_off': 'Log Off',
        'shopping_cart': 'Shopping Cart',
        'name': 'Name',
        'price': 'Price',
        'total': 'Total:',
        'clear_all': 'Clear all',
        'purchase': 'Purchase',
        'double_click': 'Double-click or drag to add to cart',
        'my_favorite': 'My favorite',
        'my_last_purchase': 'My last purchase',
        'company_favorite': 'Company favorite',
        'bartender_pick': 'Bartender\'s pick',
        'what': 'What',
        'when': 'When',
        'amount': 'Amount',
        'balance_history_stats': 'Balance',
        'stock': 'Stock',
        'users': 'Users',
        'machine_content': 'Machine Content',
        'double_click_edit': 'Double-click to Edit',
        'add_new_beverage': 'Add New Beverage',
        'add_new_user': 'Add New User',
        'username': 'Username',
        'debt': 'Debt',
        'admin_question': 'Is Admin?',
        'edit_machine_content': 'Edit Machine Content'
    },
    'swe': {
        'all_beverages': 'Alla dryck',
        'soft_drinks': 'Utan alkohol',
        'alcoholic_drinks': 'Alkoholhaltiga',
        'history_stats': 'Historia/Statistik',
        'welcome': 'Välkommen',
        'balance': 'Balans:',
        'admin_view': 'Admin vy',
        'log_off': 'Logga ut',
        'shopping_cart': 'Kundvagn',
        'name': 'Namn',
        'price': 'Pris',
        'total': 'Summa:',
        'clear_all': 'Tömma',
        'purchase': 'Köp',
        'double_click': 'Dubbelklicka eller dra för att lägga till i kundvagnen',
        'my_favorite': 'Min favorit',
        'my_last_purchase': 'Mitt senaste köp',
        'company_favorite': 'Företagets favorit',
        'bartender_pick': 'Barmästarens val',
        'what': 'Vad',
        'when': 'När',
        'amount': 'Mängd',
        'balance_history_stats': 'Balans',
        'stock': 'Lager',
        'users': 'Användare',
        'machine_content': 'Maskin innehåll',
        'double_click_edit': 'Dubbelklicka för att redigera',
        'add_new_beverage': 'Lägg till en dryck',
        'add_new_user': 'Lägg till en ny användare',
        'username': 'Användarnamn',
        'debt': 'Skuld',
        'admin_question': 'Är admin?',
        'edit_machine_content': 'Redigera maskinens innehåll'
    }
};