var arrLang = {
    'en': {
        'all_beverages': 'All Beverages',
        'soft_drinks': 'Soft Drinks',
        'alcoholic_drinks': 'Alcoholic Drinks',
        'history_stats': 'History/Stats',
        'welcome': 'Welcome',
        'balance_colon': 'Balance:',
        'admin_view': 'Admin view',
        'log_off': 'Log Off',
        'shopping_cart': 'Shopping Cart',
        'name': 'Name',
        'price': 'Price',
        'total': 'Total:',
        'clear_all': 'Clear all',
        'purchase': 'Purchase',
        'double_click': 'Double-click or drag to add to cart',
        'my_favorite': 'My favorite',
        'my_last_purchase': 'My last purchase',
        'company_favorite': 'Company favorite',
        'bartender_pick': 'Bartender\'s pick',
        'what': 'What',
        'when': 'When',
        'amount': 'Amount',
        'balance': 'Balance',
        'stock': 'Stock',
        'users': 'Users',
        'machine_content': 'Machine Content',
        'double_click_edit': 'Double-click to Edit',
        'add_new_beverage': 'Add New Beverage',
        'add_new_user': 'Add New User',
        'username': 'Username',
        'debt': 'Debt',
        'admin_question': 'Is Admin?',
        'edit_machine_content': 'Edit Machine Content',
        'update_amount_in_machine': 'Update the amount in the machine',
        'save': 'Save',
        'cancel': 'Cancel',
        'edit_user_info': 'Edit User Info',
        'password': 'Password',
        'email': 'Email address',
        'phone_number': 'Phone number',
        'admin_powers': 'Admin Powers',
        'edit_bev_info': 'Edit Beverage Info',
        'bev_name': 'Beverage name',
        'quantity_in_stock': 'Quantity in stock',
        'bev_price': 'Price of beverage',
        'bev_type': 'Beverage type',
        'select_bev': ' -- select a beverage -- ',
        'soft_drink': 'Soft Drink',
        'lager': 'Lager',
        'stout': 'Stout',
        'ale': 'Ale',
        'beer': 'Beer',
        'white_wine': 'White Wine',
        'red_wine': 'Red Wine',
        'cider': 'Cider',
        'alcoholic': 'Alcoholic?',
        'reset': 'Reset',
        '': '',
    },
    'swe': {
        'all_beverages': 'Alla dryck',
        'soft_drinks': 'Utan alkohol',
        'alcoholic_drinks': 'Alkoholhaltiga',
        'history_stats': 'Historia/Statistik',
        'welcome': 'Välkommen',
        'balance_colon': 'Balans:',
        'admin_view': 'Admin vy',
        'log_off': 'Logga ut',
        'shopping_cart': 'Kundvagn',
        'name': 'Namn',
        'price': 'Pris',
        'total': 'Summa:',
        'clear_all': 'Tömma',
        'purchase': 'Köp',
        'double_click': 'Dubbelklicka eller dra för att lägga till i kundvagnen',
        'my_favorite': 'Min favorit',
        'my_last_purchase': 'Mitt senaste köp',
        'company_favorite': 'Företagets favorit',
        'bartender_pick': 'Barmästarens val',
        'what': 'Vad',
        'when': 'När',
        'amount': 'Mängd',
        'balance': 'Balans',
        'stock': 'Lager',
        'users': 'Användare',
        'machine_content': 'Maskin innehåll',
        'double_click_edit': 'Dubbelklicka för att redigera',
        'add_new_beverage': 'Lägg till ett dryck',
        'add_new_user': 'Lägg till en ny användare',
        'username': 'Användarnamn',
        'debt': 'Skuld',
        'admin_question': 'Är admin?',
        'edit_machine_content': 'Redigera maskinens innehåll',
        'update_amount_in_machine': 'Updatera mängden in maskinen',
        'save': 'Spara',
        'cancel': 'Avbryt',
        'edit_user_info': 'Redigera användarinfo',
        'password': 'Lösenordet',
        'email': 'Email adress',
        'phone_number': 'Telefonnummer',
        'admin_powers': 'Admin rättigheterna',
        'soft_drink': 'Alkoholfritt',
        'edit_bev_info': 'Redigera dryck info',
        'bev_name': 'Dryck namn',
        'quantity_in_stock': 'Antalet i lagret',
        'bev_price': 'Dryckpris',
        'bev_type': 'Drycktyp',
        'select_bev': ' -- välj ett dryck -- ',
        'soft_drink': 'Alkoholfritt',
        'lager': 'Lager',
        'stout': 'Stout',
        'ale': 'Ale',
        'beer': 'Öl',
        'white_wine': 'Vit vin',
        'red_wine': 'Rött vin',
        'cider': 'Cider',
        'alcoholic': 'Alkoholhaltigt?',
        'reset': 'Nollställ',
    }
};